all : bitrev bitrev_counter kbit_rev_permute

bitrev : bitrev.c
	gcc -Wall --std=gnu99 -o bitrev bitrev.c -lm

bitrev_counter : bitrev_counter.c
	gcc -Wall --std=gnu99 -o bitrev_counter bitrev_counter.c -lm

kbit_rev_permute : kbit_rev_permute.c
	gcc -Wall --std=gnu99 -o kbit_rev_permute kbit_rev_permute.c -lm